### ISSUE TITLE
setMyCommands

### ISSUE THREAD

**Issue by Splatter-dev** [eternnoir/pyTelegramBotAPI#1129]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?  3.7.7

2. What OS are you using? Linux

3. What version of python are you using? 3.7.5

Hi,

dic = [{"command" : "first", "description" : "first command"}]
dic_json = json.dumps(dic)

test = bot.set_my_commands(dic_json)
print(test)

The test returns True but doesn't set my command.

**Comment by d-maxime** [comment]
Your string seems correct and I don't know what happens inside the bot.set_my_commands method but I can tell you what I had to do to get the command accepted by telegram because what you have to send is an array and not a dictionary:
I had to add a \ before each double quotes:
tsend setmycommands commands = [{\\"command\": \\"help\", \\"description\\": \\"help description\\"}]
to make the sent command become:
[{"command": "help", "description": "help description"}]
and was accepted.
Hope this can help you.
cheers
