### ISSUE TITLE
Is it possible to enable retry mechanism by default

### ISSUE THREAD

**Issue by ofen** [eternnoir/pyTelegramBotAPI#1291]
I find retry mechanism implementation in `telebot/apihelper.py` is quite useful due to network nature. Is it possible to enable it by default (see https://github.com/eternnoir/pyTelegramBotAPI/blob/master/telebot/apihelper.py#L38)?

P.S. currently it could be enabled manually via
```py
import telebot

telebot.apihelper.RETRY_ON_ERROR = True
...
```

**Comment by Badiboy** [comment]
What is the problem with enabling it manually?

**Comment by ofen** [comment]
it's just my opinion but this reduce configuration bloat and allow users to work with lib out-of-the-box without using try/catch on each method or reading `apihelper.py` code.

**Comment by coder2020official** [comment]
@Badiboy do you think it is good to be True by default? I think setting True by default will be better

**Comment by Badiboy** [comment]
@coder2020official I had no strong oppinion on this question.  But I stand for saving behavior compatibility.

Simple example. In my project I prefer short user sessions instead of 100% message delivery. Because of haveing dozens of users.

I have 10 seconds connection timeout. If you change RETRY_ON_ERROR = True for me, in some unpredictable cases I'll have:
connection_timeout (10) * RETRY_TIMEOUT (2) * MAX_RETRIES (15) = 300.
THREE HUNDRED SECONDS session.

How do you think, what words I'll say to developers who will change MY SYSTEM behaviour to this?

**Comment by coder2020official** [comment]
Well, retrying on error by default would be good, but ok, let it stay how it was

**Comment by coder2020official** [comment]
Can we close this issue?
