### ISSUE TITLE
Wrong api token goes silent

### ISSUE THREAD

**Issue by igormcsouza** [eternnoir/pyTelegramBotAPI#1312]
I got an error that I just couldn't understand where was it.. No feedback and anything. After a lot of time debugging I found it was a wrong api token (an empty string). But it rings a bell for me, because I was using try/except on the bot definition. I went into this package code and found the error.

When checks for problems with API token, it just runs a simple is none check, see [line](https://github.com/eternnoir/pyTelegramBotAPI/blob/c6ff9b07df9438c401f26e330801be8ea92925e1/telebot/apihelper.py#L76).

The write method is to check if the given string is actually a token.

**Comment by Badiboy** [comment]
1. Works fine.
![image](https://user-images.githubusercontent.com/5613421/134070123-2ad6ab35-fed8-440c-86fa-68a045d56416.png)

2. You should learn better how expressions like "not string" work.

**Comment by igormcsouza** [comment]
It wasn't throwing an error! The fix for me was to assert at the beginning and through an Assertion Error... Even though, the way it is written on the bot doesn't seem to be ok! A better way can be done! As soon as I can, I will open a PR for that! :)

**Comment by w3Abhishek** [comment]
Can i work on this issue?

**Comment by Badiboy** [comment]
> It wasn't throwing an error!

So it works for me, works for others, not works for you. You do not know how "not" works with various data types... And you still think the problem is in library and plan to PR?... Looks strange.

**Comment by Badiboy** [comment]
> Can i work on this issue?

No issue.

**Comment by igormcsouza** [comment]
I'm sorry @Badiboy ... It looks like you're not welcome improvements?

I found this regex Telegram API Token validation, it is better than check if the token was provided or not...

https://www.regextester.com/108794

@w3Abhishek If you want to open a PR with this it will be great! I'll help as soon as I can!

**Comment by Badiboy** [comment]
> It looks like you're not welcome improvements?

I do not welcome fantasies and incorrect issues. The library definitely raises the exception and I proofed you this. If you do not have exception - you should check your code where the exception is hidden.



> it is better than check if the token was provided or not...

It is not better. Empty string is a mistake of the developer: it means he **forget** to pass token? so library informs him. If the developer is so dumb that he do not know what the crap he passes as token - I do not think that library should care about such developers.

Anyway telegram will inform developer that he passed crap instead of token by not accepting this token at the very first request. So there is no need for any token processing in library.

**Comment by igormcsouza** [comment]
That message was aggressive and disrespectful. If this tool is open source, improvements and comments can be made and all of them should be treated with cordiality and respect! I'm reporting this to Github and hopes @eternnoir take the necessary steps!
