### ISSUE TITLE
ERROR AsyncTeleBot Request timeout & TypeError in logging

### ISSUE THREAD

**Issue by shaprinskiy** [eternnoir/pyTelegramBotAPI#2028]
Hi,

Addition information:
1. Version of pyTelegramBotAPI - 4.12.0
2. OS - Linux 5.4.0-150-generic (#167-Ubuntu GNU/Linux)
3. Version of python - 3.9.0

Problem - logging stopped due to a timeout during operation of asynctelebot
The log of this event is attached.
[error_log.txt](https://github.com/eternnoir/pyTelegramBotAPI/files/12342374/error_log.txt)

**Comment by NoxiousDream** [comment]
It isn't an async, srry

**Comment by shaprinskiy** [comment]
Please describe. I didn't understand the answer, because in code used: from telebot.async_telebot import AsyncTeleBot  16.08.2023, 01:11, "NoxiousDream" ***@***.***>: It isn't an async, srry—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by shaprinskiy** [comment]
ok, it's problem in Aiohttp library, not in pyTelegramBotAPI

**Comment by Badiboy** [comment]
![image](https://github.com/eternnoir/pyTelegramBotAPI/assets/5613421/7ba4c4c3-4386-464f-bec5-1843172416bf)

From your log you can obviously see:
1. Error appears in python logging library
2. Someone corrupt the Handler.backupCount value by setting in to string instead of int.

If you inspect logger, you can obviously see that backupCount is used only in Rotating File Handlers.

If you inspect pyTelegramBotAPI code you can obviously see that library creates only STREAM HANDLER and do not create file handlers, especially Rotating.

Now it's time to find, who created Rotating handler and did it wrong, by passing string to backupCount on initialization.
I have a suspicion who did this but I'll left this suscpicion with me for now.
