### ISSUE TITLE
Bot doesn't handle the message if there is a symbol inside.

### ISSUE THREAD

**Issue by Steve707-AE** [eternnoir/pyTelegramBotAPI#2116]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
4.14.1
2. What OS are you using?
Windows
3. What version of python are you using?
3.11

@bot.message_handler()
async def handle_track_code(message: types.Message):
    print(message)

I have this simple code, no filters. If from the bot I send a message like AAAA:BBBB the bot doesn't handle the message, as for AAAA BBBB or AAAA,BBBB. Is it only an issue of mine? Thanks.

**Comment by coder2020official** [comment]
Can you share your full code? So the bot isn't handling any messages?

**Comment by Darkless012** [comment]
Well what a coincidence with timimng, I'm solving the same or similar issue right now.

My trace is 
```
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: can't parse entities: Character '.' is reserved and must be escaped with the preceding '\'
```
And sending it with:
```
bot.send_message(chat_id=chat_id, text=text, parse_mode="Markdown")
```
and text containing a special char ("." dot in my case) but also produced with "!" exclamation mark

As a **workaround** I've escaped the text with:
```
text = telebot.formatting.escape_markdown(text)
bot.send_message(chat_id=chat_id, text=text, parse_mode="Markdown")
```
The problem is that the formatting is not applied at all with the escaping.

There is no difference between using "Markdown" and "MarkdownV2" in parse_mode in my case.
So I'm deducing that **MarkdownV2** went as default now or **Markdown** was removed?

For the completeness I'm adding link to the API definition: https://core.telegram.org/bots/api#markdownv2-style

**Comment by Badiboy** [comment]
> So I'm deducing that **MarkdownV2** went as default now or **Markdown** was removed?

Nothing changed. Most probably you set default parse_mode when creating Telebot instance.

**Comment by Steve707-AE** [comment]
My issue is related when I have to handle a message including symbol from telegram. 
`@bot.message_handler()
async def symbol_dot_test(message: types.Message):
    mylogger.info(message.text)
    await bot.reply_to(message, 'Hello')`

![telegram](https://github.com/eternnoir/pyTelegramBotAPI/assets/72551650/f0a7f069-ebe2-4d38-a019-e9cce5cd84ba)
![python](https://github.com/eternnoir/pyTelegramBotAPI/assets/72551650/b2c6b1ca-4547-4842-b16f-750708475f23)
As you see, if I send a message like the first the bot answer and log the message, but if I sent a message like the second example, the bot doesn't handle the message at all!

**Comment by Badiboy** [comment]
Try to send 2 simple messages. Like 
AAA
(hello)
BBB
(??)

Will the bot answer?
