### ISSUE TITLE
HTTPSConnectionPool

### ISSUE THREAD

**Issue by vasileknik76** [eternnoir/pyTelegramBotAPI#241]
I have Python v2.7.10, pyTelegramBotAPI v2.1.7 and Ubuntu 15.10
During runtime using polling, I sometimes get an error:
**HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=3.5)**
or
**HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=30)**

Sometimes it happens every ten minutes, but other times bot works for days without errors.
I tried to put the bot's code into try block inside an infinity loop, but today today bot stopped responding to messages and I had to restart it. Here is the structure of my code:
**bot.py**:

```
import engine
while True:
        try:
            reload(engine)
            engine.main()
        except (Timeout, ReadTimeoutError, ConnectionError) as err:
            log.e("%s\n\nError occured, but bot will restart in 20s.", err.__str__())
            time.sleep(20)
```

**engine.py:**

```
bot = telebot.TeleBot(token)
...
#Here are some handlers and functions
...

def main(): 

    bot.polling(none_stop=True)
```

I can't understand  where the problem is: connection error, bug in my code or in the library.
Can anybody help me?
UPD: Just found similar issue, but I still can't understand how to fix this error.
[https://github.com/eternnoir/pyTelegramBotAPI/issues/206](https://github.com/eternnoir/pyTelegramBotAPI/issues/206)

**Comment by denisergashbaev** [comment]
why not catching all exceptions?, ie
```
while True:
   try:
      foo()
   except Exception as e:
      log_it()
```

**Comment by MonsterDeveloper** [comment]
I had that problem too. (Yes, yes. It is actual even now). When my bot's users were ~200 that was not too bad, but not good anyways. But now around 700 people use my bot, so I decided to move to `Webhooks` instead of buggy long polling. I don't have this problem now, because Telegram pushes new updates directly to my bot so I don't need to request updates manually, like I did with long polling. I recommend you to move to Webhooks too. Also, there is a good example with CherryPy: https://github.com/eternnoir/pyTelegramBotAPI/blob/master/examples/webhook_examples/webhook_cherrypy_echo_bot.py.
