### ISSUE TITLE
getUpdates (longpolling) vs. WebHooks. What is better?

### ISSUE THREAD

**Issue by MonsterDeveloper** [eternnoir/pyTelegramBotAPI#288]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using? Latest

2. What OS are you using? Ubuntu 16.04

3. What version of python are you using? Python 3.5
I wonder: in which cases it is better to use webhooks or longpolling? What method is better? When it is better to use webhooks instead of longpolling?

**Comment by Gooman-rus** [comment]
I think that WebHook is better when you need a reliable bot that will never go offline because of telegram servers lags. But it requires SSL cetificate (you can sign it by yourself) and separate HTTP server with IP address and access to it from the Internet. 

So if this is not a problem, you need to use the WebHook.

**Comment by MonsterDeveloper** [comment]
Thanks! Nice answer) Closing issue.
