### ISSUE TITLE
Bot doesn't read any characters but latin

### ISSUE THREAD

**Issue by BenedictBaxter** [eternnoir/pyTelegramBotAPI#379]
Bot don't do print(message) if message text has any characters but latin.

Here's the code:
```python
@bot.message_handler(func=lambda message: True, content_types=['text'])
def echo_message(message):
	print('echo #1')
	bot.reply_to(message, message.text)
	print('echo #2')
	bot.reply_to(message, message.text)
	print(message)
```	

Here's requests:
![2017-07-29_13-27-52](https://user-images.githubusercontent.com/30548756/28744053-d3af4d34-7461-11e7-8644-2a93d1a956ff.png)

And this is console:
![2017-07-29_13-12-02](https://user-images.githubusercontent.com/30548756/28744043-6fee1cc6-7461-11e7-932c-0f5989111885.png)

Another code:
```python
@bot.message_handler(func=lambda message: True, content_types=['text'])
def echo_message(message):
	print('echo #1')
	bot.reply_to(message, message.text)
	print('echo message')
	print(message.text)
	print('echo #2')
	bot.reply_to(message, message.text)
	print(message)	
```
Requests:
![2017-07-29_13-30-00](https://user-images.githubusercontent.com/30548756/28744066-1953bb04-7462-11e7-8dae-215e109ba633.png)

And console:
![2017-07-29_13-14-45](https://user-images.githubusercontent.com/30548756/28744069-2781f5e2-7462-11e7-8161-d3c3e7cc8032.png)

You may notice that bot can't print message to the console, but echoes correctly in the 1st example and if I add `print(message.text)` between 2 echos, there's no 2nd echo in the 2nd example.

Setup:
pyTelegramBotAPI 3.1.0
centos7-x86_64
python 3.6

**Comment by pedrohma95** [comment]
Hello @BenedictBaxter !

Looks like you are forgetting to convert the message to encoding utf-8.

Try this code:

```python
@bot.message_handler(func=lambda message: True, content_types=['text'])
def echo_message(message):
    s = message.text.encode('utf-8')
    message.text = s
    bot.reply_to(message, message.text)
    print(message)
    print(s)
```

After running this code i got the following output:

![image](https://user-images.githubusercontent.com/6583751/40073211-1733705a-582b-11e8-8743-8ff03faa49c2.png)

![image](https://user-images.githubusercontent.com/6583751/40074021-572c74c0-582d-11e8-95fb-243534774929.png)

For the first message I sent **здороваться** and if you see my console the text is displayed as `'text': '\xd0\xb7\xd0\xb4\xd0\xbe\xd1\x80\xd0\xbe\xd0\xb2\xd0\xb0\xd1\x82\xd1\x8c\xd1\x81\xd1\x8f'` because it's not encoded.
For the second message I sent **latin** and in the console is displayed as `'text': 'latin'` because it is encoded using utf-8.
