### ISSUE TITLE
 How to send data from a json by message?

### ISSUE THREAD

**Issue by prdricardo** [eternnoir/pyTelegramBotAPI#677]
Hello, sorry for my bad english, I'm brazilian.
I'm using the step-by-step example, I'm trying to make sure that when a person calls a / zip function for example he asks to type a zip code that would be zipcode and when you enter enter python consult json and bot send a response does anyone have an example with this?
I'm a few days headbanging.
i'm trying with json: https://viacep.com.br/ws/99709252/json/
and the most I could do is list in the terminal :(
What I have now
```
`@bot.message_handler(commands=['cep'])
def send_welcome(message):
msg = bot.reply_to(message, "Olá, Qual seu CEP?")
bot.register_next_step_handler(msg, consulta_cep)


def consulta_cep(message):
with urllib.request.urlopen("https://viacep.com.br/ws/99709252/json/") as url:
data = json.loads(url.read().decode())
print(data)
```
`
I tried to put the text typed in json, I couldn't either, I think I can do the first one, I can apply it to other jsons

Thank you!

**Comment by jpcst** [comment]
I suppose your problem is to send the scraped json data to the user? I personally like to use the requests module.
The following code is not what you asked but maybe it can help you out, it's just an example so you can make your own thing work.
```
import telebot, requests, json
url = 'https://viacep.com.br/ws/99709252/json/'
data = requests.get(url).json()
zip = data['cep']
rua = data['logradouro']
out = zip + '\n' + rua
tb.send_message(id, out)
```
(Também sou BR, se tiver dificuldade no inglês e quiser perguntar algo mais complexo algo fique a vontade)
