### ISSUE TITLE
Problem when defining bot within a class: TypeError: send_message() missing 1 required positional argument: 'message'

### ISSUE THREAD

**Issue by TonserTorben** [eternnoir/pyTelegramBotAPI#710]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using? 3.6.6

2. What OS are you using? Windows 10

3. What version of python are you using? 3.7

I am trying to define the telegram bot within a class like so: 
class TelegramManager(AbstractMessagingManager):

    api_key = config('TELEGRAM_TOKEN')        

    bot = telebot.TeleBot(api_key)

    @bot.message_handler(func=lambda message: True)
    def send_message(self, message):
        msg = message
        print(msg.text)
        intent = dialog.askGoogle(msg.text)
        reply =  execution.findAnswer(intent)
        self.bot.reply_to(msg, reply)

But when sending a message to the bot via Telegram, python gives a TypeError, see below:
TypeError: send_message() missing 1 required positional argument: 'message'

Is it not possible to define the bot and message_handler within a class?

**Comment by keshamin** [comment]
@TonserTorben 
The reason is that `self` argument is automatically passed to a method when it is called via `.` (dot). Like here:
```
tm = TelegramManager()
tm.send_message(msg)    # self is passed automatically
```

In your code `send_message()` method of `TelegramManager` is called by an instance of `TeleBot`, so it works like a regular function with 2 arguments: `self, message`. `TeleBot` passes an instance of `Message` to the first argument and the second one is missing.

I believe that you can define this handler as a regular function but not a method of `TelegramManager` class. For example in `__init__()` method:
```
class TelegramManager(...):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.bot = telebot.TeleBot(config('TELEGRAM_TOKEN'))

        @self.bot.message_handler(func=lambda m: True)
        def handler(message):
            self.bot.reply_to(message, 'Put your reply here!')
```
